import Head from "next/head";
import LoginTest from "@/components/login/LoginTest";
import { signIn, signOut, useSession } from "next-auth/client";

export default function Home({ allSpences, totalSpences }) {
  const [session, loading] = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session && (
        <div className="flex items-center justify-center h-screen">
          <div className="flex flex-col w-full max-w-sm px-4 py-8 bg-white rounded-lg shadow dark:bg-gray-800 sm:px-6 md:px-8 lg:px-10">
            <div className="self-center text-2xl font-bold text-gray-600 sm:text-2xl dark:text-white">
              Device Register App
            </div>
            <div className="m-6 text-xl text-center">Not signed in</div>
            <button
              className="block px-4 py-2 text-base font-semibold text-center text-white transition duration-200 ease-in bg-purple-600 rounded-lg shadow-md hover:bg-purple-700 focus:ring-purple-500 focus:ring-offset-purple-200 focus:outline-none focus:ring-2 focus:ring-offset-2"
              onClick={() => signIn()}
            >
              Sign in
            </button>
          </div>
        </div>
      )}
      {session && (
        <>
          <div className="p-4">
            <nav className="items-center justify-between px-8 sm:flex">
              <div className="text-2xl font-bold text-gray-700">Devices</div>

              <div className="flex items-center space-x-8">
                <div className="text-xl font-medium text-gray-700">
                  Signed in as{" "}
                  <span className="font-bold">{session.user.name}</span>
                </div>
                <button
                  className="block px-4 py-2 text-base font-semibold text-center text-white transition duration-200 ease-in bg-red-500 rounded-lg shadow-md hover:bg-red-600 focus:ring-red-500 focus:ring-offset-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2"
                  onClick={() => signOut()}
                >
                  Sign out
                </button>
              </div>
            </nav>
          </div>
        </>
      )}
    </>
  );
}
